version: "2.0"

services:
  express-api7:
    build: ./api
    container_name: express-api7
    restart: always
    ports:
      - "3000:80"
    environment:
      - SERVER_PORT=3000
      - PORT=80
      - DATABASE_URL=${DATABASE_URL}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
    command: ["npm", "start"]
