version: "2.0"

services:
  express-api:
    build: ./api
    container_name: express_api
    restart: always
    ports:
      - "3000:80"
    environment:
      - SERVER_PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
    command: ["npm", "start"]
