version: "2.0"

services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=${DOCKER_DB_USER} #postgres
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD} #postgres123
      - POSTGRES_DB=${DOCKER_DB_NAME} #chas_advance_db
    #  - POSTGRES_PORT=${DOCKER_DB_PORT} #5432
    #  - POSTGRES_HOST=${DOCKER_DB_HOST} #localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tables/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  express-api:
    build: ./api
    container_name: express-api7
    restart: always
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      - SERVER_PORT=3000
      - PORT=80
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PGUSER=${DOCKER_DB_USER}
      - PGPASSWORD=${DOCKER_DB_PASSWORD}
      - PGDATABASE=${DOCKER_DB_NAME}
      - PGHOST=postgres_db
      - PGPORT=5432
    command: ["npm", "start"]

volumes:
  postgres_data:
