name: CI #namnet på ens workflow

on: #Vad som triggar en workflow
  push:
    branches: ["dev", "feature"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs: #jobs är stegen som körs sekvent av en virtuell maskin
  build:
    runs-on: ubuntu-latest
    steps: # steg i pipelinen
      - uses: actions/checkout@v3 #Hämtar koden från repot
      - name: Use Node.js
        uses: actions/setup-node@v3 #Sätter upp e node enviroment med v20
        with:
          node-version: "20"

      - name: packageInstall
        run: |
          cd api  
          npm install
      - name: typecheck
        run: |
          cd api  
          npm run typecheck
      - name: build
        run: |
          cd api  
          npm run build
