name: Azure setup

on:
  push:
    branches: ["feature"]
  workflow_dispatch:

jobs:
  azure_login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ secrets.ACR_URL }} -u ${{ secrets.ACRUSERNAME }} -p ${{ secrets.ACRPASSWORD1 }}

      - name: Build and test API image
        run: |
          docker build -t ${{ secrets.ACR_URL }}/api:latestLogin ./api
          docker run --rm ${{ secrets.ACR_URL }}/api:latestLogin npm test

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_URL }}/api:latestLogin

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "express-api7"
          images: ${{ secrets.ACR_URL }}/api:latestLogin
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
